name: Windows VM with VNC Access

on:
  push:
    branches:
      - main

jobs:
  windows-vm:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Chocolatey
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force; `
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; `
          iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

      - name: Install TightVNC
        run: |
          choco install tightvnc --params "/norestart /quiet" -y

      - name: Start TightVNC Server
        run: |
          Start-Process -FilePath "C:\Program Files\TightVNC\tvnserver.exe" -ArgumentList "-run"

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Localtunnel
        run: npm install -g localtunnel

      - name: Start Localtunnel and Print URL
        run: |
          node -e "const lt = require('localtunnel'); lt({ port: 5900, subdomain: 'your-subdomain' }, (err, tunnel) => { if (err) { console.error(err); process.exit(1); } console.log('Localtunnel URL:', tunnel.url); });" &

      - name: Keep alive
        run: Start-Sleep -Seconds 3600
